grammar Wordlify;
startRule: (ASSIGNEMENT|DOWNLOAD|COPY)+;

ID: [A-Za-z]+[0-9]*;
WHITESPACE: [ \r\n\t]+ -> channel (HIDDEN);
EQUAL: WHITESPACE '=' WHITESPACE;
NEWLINE: [\n];
ASSIGNEMENT: ID EQUAL (INTEGER|STRING) NEWLINE?;
INTEGER: [0-9]+;
STRING: '"'.*?'"';
DOWNLOAD: 'download' WHITESPACE (ID|STRING) (ID|STRING)? NEWLINE?;
COPY: 'copy' WHITESPACE (ID|STRING) (ID|STRING) NEWLINE?;
REMOVE: 'remove' WHITESPACE (ID|STRING) NEWLINE?;
